accepted = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "GPL-3.0-or-later",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "MPL-2.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "bzip2-1.0.6",
]
