#![allow(dead_code)]
#![allow(clippy::all, clippy::nursery, clippy::pedantic, clippy::restriction)]

// This file is @generated by prost-build.
/// Control is a bsdiff operation, see <https://twitter.com/fasterthanlime/status/790617515009437701>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Control {
  #[prost(bytes = "vec", tag = "1")]
  pub add: ::prost::alloc::vec::Vec<u8>,
  #[prost(bytes = "vec", tag = "2")]
  pub copy: ::prost::alloc::vec::Vec<u8>,
  #[prost(int64, tag = "3")]
  pub seek: i64,
  /// when true, don't apply and stop reading bsdiff control
  #[prost(bool, tag = "4")]
  pub eof: bool,
}
