mod code_verifier;
mod uuid;

pub use code_verifier::{CodeChallenge, CodeVerifier};
pub use uuid::UuidV4;

use super::errors::{ItchRequestJSONError, OauthResponseError};
use super::responses::OAuthTokenResponse;
use super::types::OAuthToken;
use super::{ItchApiUrl, ItchClient};

use reqwest::{Method, Url};

/// itch.io OAuth 2.0 authorization endpoint
const URL_ENDPOINT: &str = "https://itch.io/user/oauth";
const RESPONSE_TYPE: &str = "code";
/// OAuth client ID used by the itch.io APP
///
/// <https://github.com/itchio/itch/blob/3a9c33a654e55e039bc0ae5155d83fb0ddd1aca2/src/main/reactors/login.ts#L29>
const CLIENT_ID: &str = "85252daf268d27fbefac93e1ac462bfd";
const REDIRECT_URI: &str = "itch://oauth-callback";
const SCOPE: &str = "itch";
/// SHA-256 code challenge method, as defined in [RFC 7636 §4.2](https://datatracker.ietf.org/doc/html/rfc7636#section-4.2)
const CODE_CHALLENGE_METHOD: &str = "S256";

/// The authorization URL and code verifier for an OAuth 2.0 PKCE flow
pub struct OAuthRequest {
  /// The authorization URL to open in the browser
  pub url: String,
  /// A unique identifier for this OAuth request
  pub state: UuidV4,
  /// The code verifier to use in the token exchange after the user authorizes
  pub code_verifier: CodeVerifier,
}

/// Build an OAuth 2.0 authorization URL with a freshly generated PKCE code verifier
///
/// # Returns
///
/// An [`OAuthRequest`] containing the authorization URL and the code verifier
/// needed for the subsequent [`exchange_code`] call
pub fn init() -> OAuthRequest {
  let state = uuid::UuidV4::random();
  let code_verifier = code_verifier::CodeVerifier::random();

  let url = Url::parse_with_params(
    URL_ENDPOINT,
    &[
      ("response_type", RESPONSE_TYPE),
      ("client_id", CLIENT_ID),
      ("redirect_uri", REDIRECT_URI),
      ("scope", SCOPE),
      ("state", state.as_str()),
      ("code_challenge_method", CODE_CHALLENGE_METHOD),
      ("code_challenge", code_verifier.to_challenge().as_str()),
    ],
  )
  .expect("base URL is always valid");

  OAuthRequest {
    url: url.to_string(),
    state,
    code_verifier,
  }
}

/// Exchange an authorization code for an OAuth token using PKCE
///
/// # Arguments
///
/// * `client` - An itch.io API client. It can be unauthorized.
///
/// * `code_verifier` - The code verifier generated by [`init`]
///
/// * `authorization_code` - The authorization code received from the OAuth callback
///
/// # Returns
///
/// A [`OAuthToken`] struct with the info provided by the API
///
/// # Errors
///
/// If the request, retrieving its text, or parsing fails, or if the server returned an error
pub fn exchange_code(
  client: &ItchClient,
  code_verifier: &str,
  authorization_code: &str,
) -> Result<OAuthToken, ItchRequestJSONError<OauthResponseError>> {
  client
    .itch_request_json::<OAuthTokenResponse>(&ItchApiUrl::v2("oauth/token"), Method::POST, |b| {
      b.form(&[
        ("grant_type", "authorization_code"),
        ("code", authorization_code),
        ("code_verifier", code_verifier),
        ("redirect_uri", REDIRECT_URI),
        ("client_id", CLIENT_ID),
      ])
    })
    .map(|res| res.token)
}
