use crate::config::Config;
use crate::eprintln_exit;

use clap::Subcommand;
use scratch_io::ItchClient;
use scratch_io::itch_api::{endpoints, oauth};

#[derive(Subcommand)]
pub enum SessionCommand {
  /// Print the currently saved API key
  PrintKey,
  /// Remove the saved API key
  Logout,
  /// Log in with an API key
  Auth {
    /// The API key to save
    api_key: String,
  },
  /// Log in using OAuth 2.0 with PKCE
  #[clap(subcommand)]
  Oauth(OauthCommand),
}

#[derive(Subcommand)]
pub enum OauthCommand {
  /// Generate an authorization URL and code verifier to start the OAuth flow.
  /// Open the printed URL in your browser, then run `oauth exchange` with the returned code.
  Init,
  /// Exchange an authorization code for an API key.
  /// Requires the code verifier from `oauth init` and the authorization code from the OAuth callback.
  Exchange {
    /// The code verifier generated by `oauth init`
    #[arg(long, env = "SCRATCH_CODE_VERIFIER")]
    code_verifier: String,
    /// The authorization received code from the OAuth callback
    #[arg(long, env = "SCRATCH_AUTHORIZATION_CODE")]
    authorization_code: String,
  },
}

// Print the saved API key (if any)
fn print_key(config_api_key: &Option<String>) {
  match config_api_key {
    None => eprintln!("There isn't any API key saved!"),
    Some(key) => println!("{key}"),
  }
}

// Remove the saved API key (if any)
fn logout(config_api_key: &mut Option<String>) {
  match config_api_key {
    None => eprintln!("There isn't any API key saved!"),
    Some(_) => {
      *config_api_key = None;
      println!("Logged out.");
    }
  }
}

// Check if an api key is valid and print the user info
fn auth(api_key: String, config_api_key: &mut Option<String>) {
  // Create a client using the provided key
  let client = ItchClient::new(api_key);

  // Try to get the user info to check if the key is valid
  let profile = endpoints::get_profile(&client).unwrap_or_else(|e| eprintln_exit!("{e}"));

  // If an error hasn't been thrown, the API key is valid
  *config_api_key = Some(client.api_key().to_string());

  // Print user info
  println!(
    "Valid key!
Logged in as: {}",
    profile.user.get_name()
  );
}

fn oauth_init() {
  let oauth = oauth::get_oauth_url();

  println!(
    r#"Open this URL in your browser to authorize:
  {}

To complete the login, run the `oauth exchange` command with the following options:
  --code-verifier="{}"
  --authorization-code="{{AUTHORIZATION_CODE}}""#,
    oauth.url,
    oauth.code_verifier.as_str(),
  );
}

fn oauth_exchange(
  code_verifier: String,
  authorization_code: String,
  config_api_key: &mut Option<String>,
) {
  // Create an unauthenticated client to make the oauth request
  let client = ItchClient::unauthenticated();

  // Do the request and get the API key back from the server
  let oauth_token = oauth::exchange_code(&client, &code_verifier, &authorization_code)
    .unwrap_or_else(|e| eprintln_exit!("{e}"));

  // Check if the key is valid and save it
  println!("Successful OAuth login!");
  auth(oauth_token.access_token, config_api_key);
}

impl SessionCommand {
  pub fn handle_command(self, config: &mut Config) {
    match self {
      Self::PrintKey => print_key(&config.api_key),
      Self::Logout => logout(&mut config.api_key),
      Self::Auth { api_key } => auth(api_key, &mut config.api_key),
      Self::Oauth(OauthCommand::Init) => oauth_init(),
      Self::Oauth(OauthCommand::Exchange {
        code_verifier,
        authorization_code,
      }) => oauth_exchange(code_verifier, authorization_code, &mut config.api_key),
    }
  }
}
