name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  format:
    name: Format & Lint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}

      - name: Check code formatting
        run: cargo fmt --all -- --check --verbose

      - name: Check code lint
        run: cargo clippy --all-targets --all-features -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-tests-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Tests
        env:
          SCRATCH_API_KEY: ${{ secrets.SCRATCH_API_KEY }}
        run: cargo test --all --verbose